// Code generated by protoc-gen-go. DO NOT EDIT.
// source: req.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Entry struct {
	Term                 int64    `protobuf:"varint,1,opt,name=Term,json=term,proto3" json:"Term,omitempty"`
	LogIdx               int64    `protobuf:"varint,2,opt,name=LogIdx,json=logIdx,proto3" json:"LogIdx,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *Entry) GetLogIdx() int64 {
	if m != nil {
		return m.LogIdx
	}
	return 0
}

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Entries struct {
	E                    []*Entry `protobuf:"bytes,1,rep,name=e,proto3" json:"e,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entries) Reset()         { *m = Entries{} }
func (m *Entries) String() string { return proto.CompactTextString(m) }
func (*Entries) ProtoMessage()    {}
func (*Entries) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{1}
}

func (m *Entries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entries.Unmarshal(m, b)
}
func (m *Entries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entries.Marshal(b, m, deterministic)
}
func (m *Entries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entries.Merge(m, src)
}
func (m *Entries) XXX_Size() int {
	return xxx_messageInfo_Entries.Size(m)
}
func (m *Entries) XXX_DiscardUnknown() {
	xxx_messageInfo_Entries.DiscardUnknown(m)
}

var xxx_messageInfo_Entries proto.InternalMessageInfo

func (m *Entries) GetE() []*Entry {
	if m != nil {
		return m.E
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "pb.Entry")
	proto.RegisterType((*Entries)(nil), "pb.Entries")
}

func init() { proto.RegisterFile("req.proto", fileDescriptor_a52bd445c288993d) }

var fileDescriptor_a52bd445c288993d = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4a, 0x2d, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x8a, 0xe6, 0x62, 0x75, 0xcd, 0x2b,
	0x29, 0xaa, 0x14, 0x12, 0xe2, 0x62, 0x09, 0x49, 0x2d, 0xca, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0e, 0x62, 0x29, 0x49, 0x2d, 0xca, 0x15, 0x12, 0xe3, 0x62, 0xf3, 0xc9, 0x4f, 0xf7, 0x4c, 0xa9,
	0x90, 0x60, 0x02, 0x8b, 0xb2, 0xe5, 0x80, 0x79, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x12,
	0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x58, 0x62, 0x4e, 0x69,
	0xaa, 0x04, 0x0b, 0x58, 0x8c, 0xb5, 0x0c, 0xc4, 0x51, 0x52, 0xe2, 0x62, 0x07, 0x19, 0x9e, 0x99,
	0x5a, 0x2c, 0x24, 0xce, 0xc5, 0x98, 0x2a, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa9, 0x57,
	0x90, 0xa4, 0x07, 0xb6, 0x34, 0x88, 0x31, 0x35, 0x89, 0x0d, 0xec, 0x16, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe5, 0xe4, 0xae, 0x70, 0x98, 0x00, 0x00, 0x00,
}
